source 'https://github.com/CocoaPods/Specs.git'

platform:ios,'10.0'
#use_frameworks!

  def  commonsPods
    use_frameworks!
    pod 'Realm', '~> 5.3.3'
  end

  target "TIMClientKitDemo" do

  commonsPods
  pod 'SDWebImage', '>= 5.0.0'

  #网络请求https://github.com/yuantiku/YTKNetwork
  pod 'YTKNetwork'
  pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']

  pod 'MJRefresh'

  #RAC
  pod 'ReactiveObjC'
  #pod 'MBProgressHUD'

  #弹出菜单  https://github.com/lyb5834/YBPopupMenu
  pod 'YBPopupMenu'

  #标签https://github.com/zekunyan/TTGTagCollectionView
  pod "TTGTagCollectionView",'1.11.1'

  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          end
      end
  end
