source 'https://github.com/CocoaPods/Specs.git'

platform:ios,'10.0'
use_frameworks!
target "TIMClientKitDemo" do

pod 'Bugly'

pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug'] #必选
#pod 'DoraemonKit/WithLoad', '~> 3.0.4', :configurations => ['Debug'] #可选
#pod 'DoraemonKit/WithLogger', '~> 3.0.4', :configurations => ['Debug'] #可选
#pod 'DoraemonKit/WithDatabase', '~> 3.0.4', :configurations => ['Debug'] #可选
#pod 'DoraemonKit/WithMLeaksFinder', '~> 3.0.4', :configurations => ['Debug'] #可选
  
#网络请求https://github.com/yuantiku/YTKNetwork
pod 'YTKNetwork'
#pod 'AFNetworking'
pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']

pod 'YYModel'
pod 'YYCategories'
pod 'YYWebImage'
pod 'MJRefresh'

#RAC
pod 'ReactiveObjC'
pod 'MBProgressHUD', '~> 1.1.0'

#弹出菜单  https://github.com/lyb5834/YBPopupMenu
pod 'YBPopupMenu'

#标签https://github.com/zekunyan/TTGTagCollectionView
pod "TTGTagCollectionView"

#pod 'SDWebImage'
pod 'SDWebImage', '>= 5.0.0'

pod 'RTRootNavigationController'

#圆角处理
pod 'ZYCornerRadius'

#图片选择器
pod 'TZImagePickerController'
pod 'WZLBadge'

#键盘管理
pod 'IQKeyboardManager'

#UISegmentedControl
pod 'WMPageController'

#pod 'Realm', '~> 5.3.3'
#pod 'MLeaksFinder'

#图片浏览https://github.com/indulgeIn/YBImageBrowser
pod 'YBImageBrowser'

#pod 'AliyunOSSiOS', '>= 2.10.8'

#pod 'mobile-ffmpeg-full', '4.4.LTS'

end
